baseURL                = "https://ayanesakura.github.io/"
languageCode           = "zh-cn"
title                  = "Ruofei's Blog"
defaultContentLanguage = "zh-cn"
hasCJKLanguage         = true
theme                  = "hugo-theme-stack"

[pagination]
    pagerSize = 10

[permalinks]
    post = "/p/:slug/"
    page = "/:slug/"
