[goldmark]
  [goldmark.renderer]
    unsafe = true
  [goldmark.extensions.passthrough]
    enable = true
    [goldmark.extensions.passthrough.delimiters]
      inline = [['$', '$']]
      block = [['$$', '$$']]

[highlight]
  noClasses = false
  lineNos = true
  lineNumbersInTable = true

[tableOfContents]
  startLevel = 2
  endLevel = 4
