colorScheme = "blowfish"
defaultAppearance = "dark"
autoSwitchAppearance = true
enableSearch = true
enableCodeCopy = true
mainSections = ["posts"]
disableImageOptimization = false

[homepage]
  layout = "profile"
  homepageImage = "img/avatar.jpg"
  showRecent = true
  showRecentItems = 6
  showMoreLink = true
  showMoreLinkDest = "/posts"
  cardView = true
  cardViewScreenWidth = false

[article]
  showDate = true
  showViews = false
  showLikes = false
  showDateUpdated = true
  showAuthor = true
  showBreadcrumbs = true
  showDraftLabel = true
  showEdit = false
  showHeadingAnchors = true
  showPagination = true
  showReadingTime = true
  showTableOfContents = true
  showTaxonomies = true
  showWordCount = true
  showSummary = true
  sharingLinks = ["twitter", "reddit", "linkedin", "telegram"]

[list]
  showBreadcrumbs = true
  showTableOfContents = false
  showSummary = true
  groupByYear = true
  cardView = true

[taxonomy]
  showTermCount = true
  cardView = false
