mainSections   = ["posts"]
rssFullContent = true

[footer]
    since = 2026

[sidebar]
    emoji    = "ðŸ’»"
    subtitle = "è®°å½•æŠ€æœ¯ä¸Žç”Ÿæ´»"

[article]
    [article.license]
        enabled = false

[widgets]
    homepage = [
        { type = "search" },
        { type = "archives", params = { limit = 5 } },
        { type = "categories", params = { limit = 10 } },
        { type = "tag-cloud", params = { limit = 10 } },
    ]
    page = [{ type = "toc" }]

[comments]
    enabled = false

[colorScheme]
    toggle = true
    default = "light"
